### ISSUE TITLE
Check that btree file k value = query file number on GeneBankSearch on input parsing

### ISSUE THREAD

**Issue by ryleighmoore1** [ryleighmoore1/BTreeLab4#19]
Example ... 
* GeneBank file names:  fileName.gbk.btree.data.K.t  ... K is the sub-sequence length.
    (Some files may NOT have the ending 't' value, so parse for 'K' after "btree.data."
* Query file name: queryFileNameK  ... (K) is the subsequence length

**Comment by MJFoster** [comment]
Project specs are different than sample data filenames.  This needs to be clarified, then code updated accordingly.
