### ISSUE TITLE
calculate optimal degree of tree

### ISSUE THREAD

**Issue by joeb-bsu** [ryleighmoore1/BTreeLab4#32]
Have finished this in my branch: editTreeObject.java11.20.16 
Math needs reviewed. / tested
Look for CalculateNodeSize() method in BTree class

**Comment by MJFoster** [comment]
If you're work on a branch is completed, please create a pull request with instructions.  They are easiest to manage repos with, plus issue #'s can be referenced with them.  Thanks!

**Comment by MJFoster** [comment]
Already completed by Joe when developing BTree class.
